### ISSUE TITLE
FATAL EXCEPTION on api 19 (what is problem)?

### ISSUE THREAD

**Issue by pourya0111** [Ramotion/circle-menu-android#10]
FATAL EXCEPTION: main
                                                   Process: com.izigaaps.myapplication, PID: 15791
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.izigaaps.myapplication/com.izigaaps.myapplication.MainActivity}: android.view.InflateException: Binary XML file line #0: Error inflating class com.ramotion.circlemenu.CircleMenuView
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2342)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5421)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:979)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.ramotion.circlemenu.CircleMenuView
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                       at com.izigaaps.myapplication.MainActivity.onCreate(MainActivity.java:14)
                                                       at android.app.Activity.performCreate(Activity.java:5264)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1099)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5421) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:979) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Constructor.constructNative(Native Method)
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                       at com.izigaaps.myapplication.MainActivity.onCreate(MainActivity.java:14) 
                                                       at android.app.Activity.performCreate(Activity.java:5264) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1099) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5421) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:979) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f080067
                                                       at android.content.res.Resources.getValue(Resources.java:1169)
                                                       at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:330)
                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
                                                       at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
                                                       at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:85)
                                                       at android.support.design.widget.FloatingActionButton.setImageResource(FloatingActionButton.java:307)
                                                       at com.ramotion.circlemenu.CircleMenuView.initButtons(CircleMenuView.java:309)
                                                       at com.ramotion.circlemenu.CircleMenuView.<init>(CircleMenuView.java:161)
                                                       at com.ramotion.circlemenu.CircleMenuView.<init>(CircleMenuView.java:108)
                                                       at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                       at com.izigaaps.myapplication.MainActivity.onCreate(MainActivity.java:14) 
                                                       at android.app.Activity.performCreate(Activity.java:5264) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1099) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5421) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:979) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795) 
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by dvg4000** [comment]
Can you please provide part of your xml-layout, where you use `CircleMenuView`?

**Comment by pourya0111** [comment]
@dvg4000  it's in center of ConstraintLayout 


    `<android.support.constraint.ConstraintLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.izigaaps.myapplication.MainActivity">

    <com.ramotion.circlemenu.CircleMenuView
        android:id="@+id/circle_menu"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:button_colors="@array/colors"
        app:button_icons="@array/icons"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintHorizontal_bias="0.5"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"/>

</android.support.constraint.ConstraintLayout>`

**Comment by pourya0111** [comment]
@dvg4000 also one more question can this widget be use in service mode using windowmanager? some kine of floating overlay widget?

**Comment by dvg4000** [comment]
I guess there is wrong icon resource in `app:button_icons="@array/icons"`
`Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f080067`

I can't help you with `use in service mode using windowmanager`. `CircleViewMenu` is just an extended FrameLayout with few child-views. So if u can use `FrameLayout` as `some kine of floating overlay widget`, then you should be able to use `CircleViewMenu` too.

**Comment by pourya0111** [comment]
@dvg4000 that's not the way to resolving an issue by closing it when it's not resolved yet..
any way thanks and good luck with your library

**Comment by dvg4000** [comment]
@pourya0111, If you still have an issue, you can reopen it. Anyway i guess error comes from this method:
`FloatingActionButton.setImageResource(...)` where icons from `@array/icons` get applied to menu buttons. You can try to set drawables from that icons array, to some test `FloatingActionButton` to see if there is an error. If no, please write back, i'll try to find out where error is.
