### ISSUE TITLE
Layout Design mode - he following classes could not be instantiated: - com.ramotion.circlemenu.CircleMenuView

### ISSUE THREAD

**Issue by pravynandas** [Ramotion/circle-menu-android#26]
> When I run the app it's working fine but when I want to view the CircleMenuView in the Layout design, I'm noticing following exception. Any idea about the issue?

- circle-menu: 0.3.1
- Build tools: 27.0.3
- Gradle plugin: 3.0.1
- Android studio: 3.1.2

**Stack trace:**
java.lang.UnsupportedOperationException
	at android.content.res.Resources_Delegate.obtainTypedArray(Resources_Delegate.java:531)
	at android.content.res.Resources.obtainTypedArray(Resources.java:615)
	at com.ramotion.circlemenu.CircleMenuView.<init>(CircleMenuView.java:208)
	at com.ramotion.circlemenu.CircleMenuView.<init>(CircleMenuView.java:189)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:481)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:264)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:222)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:209)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:337)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:348)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:248)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:863)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:325)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:384)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:193)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:544)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$3(RenderTask.java:678)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by golovin47** [comment]
Hello, @pravynandas. We couldn't reproduce such issue. Also we've updated the library. So, please, try updating to new version, and if the issue still there, provide with as much detailed info about it as possible including source code, layout.xml etc. Until then this issue is considered as closed.
